[2025-05-15T18:42:51.508+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-15T18:42:51.534+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_manga_database.initialize_connections manual__2025-05-15T18:42:42.543413+00:00 [queued]>
[2025-05-15T18:42:51.550+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_manga_database.initialize_connections manual__2025-05-15T18:42:42.543413+00:00 [queued]>
[2025-05-15T18:42:51.550+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-15T18:42:51.570+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): initialize_connections> on 2025-05-15 18:42:42.543413+00:00
[2025-05-15T18:42:51.582+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=612) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-15T18:42:51.585+0000] {standard_task_runner.py:72} INFO - Started process 628 to run task
[2025-05-15T18:42:51.587+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'update_manga_database', 'initialize_connections', 'manual__2025-05-15T18:42:42.543413+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/update_manga_database_dag.py', '--cfg-path', '/tmp/tmphlwrmpf4']
[2025-05-15T18:42:51.588+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask initialize_connections
[2025-05-15T18:42:51.649+0000] {task_command.py:467} INFO - Running <TaskInstance: update_manga_database.initialize_connections manual__2025-05-15T18:42:42.543413+00:00 [running]> on host 3729034b4972
[2025-05-15T18:42:51.741+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_manga_database' AIRFLOW_CTX_TASK_ID='initialize_connections' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T18:42:42.543413+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T18:42:42.543413+00:00'
[2025-05-15T18:42:51.744+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-15T18:42:51.745+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-15T18:42:51.745+0000] {logging_mixin.py:190} INFO - Current task name:initialize_connections state:running start_date:2025-05-15 18:42:51.535112+00:00
[2025-05-15T18:42:51.746+0000] {logging_mixin.py:190} INFO - Dag name:update_manga_database and current dag run status:running
[2025-05-15T18:42:51.747+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-15T18:42:51.749+0000] {log.py:232} WARNING - 2025-05-15 18:42:51,748 - INFO: Successfully connected to PostgreSQL database
[2025-05-15T18:42:51.748+0000] {update_manga_database_dag.py:88} INFO - Successfully connected to PostgreSQL database
[2025-05-15T18:42:53.474+0000] {log.py:232} WARNING - 2025-05-15 18:42:53,474 - INFO: Successfully connected to MongoDB
[2025-05-15T18:42:53.474+0000] {update_manga_database_dag.py:95} INFO - Successfully connected to MongoDB
[2025-05-15T18:42:53.476+0000] {python.py:240} INFO - Done. Returned value was: {'pg_engine': Engine(postgresql://togiabao:***@54.160.245.147:5432/mangadex), 'mongo_collection': Collection(Database(MongoClient(host=['54.160.245.147:27017'], document_class=dict, tz_aware=False, connect=True), 'mangadex'), 'chapter_images_test')}
[2025-05-15T18:42:53.485+0000] {xcom.py:690} ERROR - Object of type Engine is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-05-15T18:42:53.488+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'sqlalchemy.engine.base.Engine'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=key, value=value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3645, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Engine is not JSON serializable
[2025-05-15T18:42:53.508+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-15T18:42:53.508+0000] {logging_mixin.py:190} INFO - Task start:2025-05-15 18:42:51.535112+00:00 end:2025-05-15 18:42:53.507517+00:00 duration:1.972405
[2025-05-15T18:42:53.509+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): initialize_connections> dag:<DAG: update_manga_database> dagrun:<DagRun update_manga_database @ 2025-05-15 18:42:42.543413+00:00: manual__2025-05-15T18:42:42.543413+00:00, state:running, queued_at: 2025-05-15 18:42:42.658956+00:00. externally triggered: True>
[2025-05-15T18:42:53.510+0000] {logging_mixin.py:190} INFO - Failure caused by Object of type Engine is not JSON serializable
[2025-05-15T18:42:53.512+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=update_manga_database, task_id=initialize_connections, run_id=manual__2025-05-15T18:42:42.543413+00:00, execution_date=20250515T184242, start_date=20250515T184251, end_date=20250515T184253
[2025-05-15T18:42:53.554+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-15T18:42:53.555+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task initialize_connections (Object of type Engine is not JSON serializable; 628)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 92, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 190, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'sqlalchemy.engine.base.Engine'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 789, in _execute_task
    task_instance.xcom_push(key=key, value=value, session=session_or_null)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3645, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 249, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 688, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 105, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 94, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Engine is not JSON serializable
[2025-05-15T18:42:53.575+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-15T18:42:53.604+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-15T18:42:53.609+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
